# See https://pre-commit.com for more information
# Get more hooks from https://pre-commit.com/hooks.html
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
        exclude: ^\.[^/]+/.*\.json$
      - id: check-toml
      - id: check-added-large-files
      ## Uncomment the following to prevent commits directly to main branch
      # - id: no-commit-to-branch
      #   args:
      #     - --branch=main
      - id: name-tests-test
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.22.1
    hooks:
      - id: markdownlint-cli2
  ## Uncomment the following to run ci checks on pre-commit
  # - repo: local
  #   hooks:
  #     - id: task-ci
  #       name: Taskfile Local Hook
  #       entry: task ci # Change 'ci' to your specific task name
  #       language: system
  #       files: \.py$ # Optional: restrict to specific file types (e.g., .go, .py)
  #       pass_filenames: false # Task usually runs on the whole repo, not just staged files
