# See https://pre-commit.com for more information
# Get more hooks from https://pre-commit.com/hooks.html
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
        exclude: ^.vscode/.*\.json$
      - id: check-toml
      - id: check-added-large-files
      ## Uncomment the following to prevent commits directly to main branch
      # - id: no-commit-to-branch
      #   args:
      #     - --branch=main
      - id: name-tests-test
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
