version: 3

vars:
  PYTHON_VERSION: "3.13"

tasks:
  default:
    desc: "Default task to run when no task is specified."
    cmd: task --list

  init:
    desc: "Initialize the project by installing dependencies."
    cmds:
      - uv python install {{.PYTHON_VERSION}} --compile-bytecode
      - uv venv --python {{.PYTHON_VERSION}} --clear
      - uv sync --compile-bytecode
      - uv run pre-commit install

  lint:
    desc: "Run linters to check code quality."
    cmds:
      - uv run ruff check

  fmt:
    desc: "Format code using uv."
    cmds:
      - uv run ruff format {{.CLI_ARGS}}

  test:
    desc: "Run tests."
    cmds:
      - uv run pytest --cov=src tests/

  test-cov:
    desc: "Run tests and generate coverage report."
    cmds:
      - uv run pytest --cov=src tests/

  ci:
    desc: "Run CI checks (lint and tests)."
    cmds:
      - task: lint
      - task: test

  sync:
    desc: "Sync the virtual environment with the lock file."
    cmds:
      - uv sync --compile-bytecode

  pre-commit:
    desc: "Run pre-commit hooks to check code before committing."
    cmds:
      - uv run pre-commit run --all-files

  dashboard-token:
    desc: "Generate a token for the Aspire dashboard."
    cmds:
      - loginLine=$(docker container logs aspire-dashboard | grep "login?t=")
      - match=$(echo "$loginLine" | sed -n 's/.*login?t=\([^[:space:]]*\).*/\1/p')
      - echo -n "$match"

  cli:
    desc: "Run the CLI application."
    cmds:
      - uv python src/cli/src/cli/main.py {{.CLI_ARGS}}
